### ISSUE TITLE
@benchmark not working

### ISSUE THREAD

**Issue by fanna** [renderedtext/ex-watchman#11]
Using 
`@benchmark(key: :auto)` or `@benchmark(key: "your_awesome_function")` wont work

only this usage works for benchmarking
`Watchman.benchmark("your_awesome_function, fn ->
  IO.puts "Sleeping"
  :timer.sleep(10000)
  IO.puts "Wake up"
end)`

**Comment by shiroyasha** [comment]
@fanna thanks for reporting. It is fixed now https://github.com/renderedtext/ex-watchman/pull/12.
